// vite-svelte/src/Pages/Posts.svelte
<script lang="ts">
    import { Router, Link, Route } from "svelte-navigator";
    import type {Post} from "../Models/Post";
    import axios from "axios";
  import { onMount } from "svelte";

    let post : Post[] = [];

    async function getData() {
        try {
            const response = await axios.get<Post[]>('https://jsonplaceholder.typicode.com/posts');
            post = response.data;
        } catch (error) {
            console.log(error);
        }
        
    }

    onMount(() => {
        getData();
    });
</script>
<main>
    <h1>Posts works!</h1>
    {#if post.length > 0}
        {#each post as post}
            <div>
                <h2>{post.title}</h2>
                <p>{post.body}</p>
            </div>
        {/each}
    {/if}
</main>

// vite-react/src/Pages/Posts.tsx
import { useState, useEffect } from 'react';
import { Post } from '../Models/Post';
const Posts = () => {

    const [listaPosts, setlistaPosts] = useState<Post[]>([]);

    useEffect(() => {
      fetchPosts();
      return () => {
      }
    }, [])
    const fetchPosts = async () => {
        const response = await fetch('https://jsonplaceholder.typicode.com/posts');
        const data = await response.json();
        setlistaPosts(data);
    }
    return (  
        <>
        {listaPosts && listaPosts.map((post) => (
            <div key={post.id}>
                <h1>{post.title}</h1>
                <p>{post.body}</p>
            </div>
        ))}
        </>
    );
}
 
export default Posts;
